openapi: 3.0.0
info:
  title: Ticket Management API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local server

paths:

  #############################
  # Admin
  #############################
  /admin/login:
    post:
      summary: Admin - Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username: { type: string }
                password: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }

  /admin/forms:
    get:
      summary: Admin - List forms
      description: "Retrieve all forms excluding those marked as deleted (is_deleted: true)."
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page: { type: integer }
                  limit: { type: integer }
                  total: { type: integer }
                  forms:
                    type: array
                    items:
                      $ref: '#/components/schemas/Form'

  /admin/forms/{formId}:
    get:
      summary: Admin - Get a specific form
      parameters:
        - in: path
          required: true
          name: formId
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Form'

    put:
      summary: Admin - Replace a form
      parameters:
        - in: path
          required: true
          name: formId
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormInput'
      responses:
        '200':
          description: Updated

    delete:
      summary: Admin - Soft delete a form
      description: Mark the form as deleted by setting `is_deleted` to `true`.
      parameters:
        - in: path
          required: true
          name: formId
          schema: { type: string }
      responses:
        '204':
          description: No Content

  /admin/tickets:
    get:
      summary: Admin - List tickets
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page: { type: integer }
                  limit: { type: integer }
                  total: { type: integer }
                  tickets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ticket'

  /admin/tickets/{ticketId}:
    get:
      summary: Admin - Get a ticket
      parameters:
        - in: path
          required: true
          name: ticketId
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'

    put:
      summary: Admin - Replace a ticket
      parameters:
        - in: path
          required: true
          name: ticketId
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketInput'
      responses:
        '200':
          description: Updated

    delete:
      summary: Admin - Soft delete a ticket
      description: Mark the ticket as deleted by setting `is_deleted` to `true`.
      parameters:
        - in: path
          required: true
          name: ticketId
          schema: { type: string }
      responses:
        '204':
          description: No Content

  /admin/movies:
    get:
      summary: Admin - List movies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'

    post:
      summary: Admin - Create movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieInput'
      responses:
        '201':
          description: Created

  /admin/movies/{movieId}/sheets:
    get:
      summary: Admin - List seats for a movie
      parameters:
        - in: path
          required: true
          name: movieId
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sheet'

    post:
      summary: Admin - Create seats for a movie
      parameters:
        - in: path
          required: true
          name: movieId
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SheetInput'
      responses:
        '201':
          description: Sheet Created

  /admin/movies/{movieId}/sheets/{sheetId}:
    get:
      summary: Admin - Get seat info
      parameters:
        - in: path
          required: true
          name: movieId
          schema: { type: string }
        - in: path
          required: true
          name: sheetId
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sheet'

    patch:
      summary: Admin - Update seat
      parameters:
        - in: path
          required: true
          name: movieId
          schema: { type: string }
        - in: path
          required: true
          name: sheetId
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated

    delete:
      summary: Admin - Delete seat
      parameters:
        - in: path
          required: true
          name: movieId
          schema: { type: string }
        - in: path
          required: true
          name: sheetId
          schema: { type: string }
      responses:
        '204':
          description: No Content

  #############################
  # User
  #############################
  /user/forms:
    post:
      summary: User - Create a new form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormInput'
      responses:
        '201':
          description: Form created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Form'

  /user/forms/{formId}:
    get:
      summary: User - Get a specific form
      parameters:
        - in: path
          required: true
          name: formId
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Form'

  /user/tickets/form/{formId}:
    get:
      summary: User - List tickets by form
      parameters:
        - in: path
          required: true
          name: formId
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'

  /user/tickets/{ticketId}:
    put:
      summary: User - Update a ticket
      parameters:
        - in: path
          required: true
          name: ticketId
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketInput'
      responses:
        '200':
          description: Updated


components:
  schemas:

    ########################################
    # Form
    ########################################
    Form:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        email: { type: string }
        is_verified: { type: boolean }
        movie_id: { type: string }
        type:
          $ref: '#/components/schemas/FormType'
        payment_method: 
          $ref: '#/components/schemas/PaymentMethod'
        payment_status:
          $ref: '#/components/schemas/PaymentStatus'
        number_of_goods_tickets: { type: integer }
        number_of_seat_tickets  : { type: integer }
        is_deleted: { type: boolean }
        remarks: { type: string, nullable: true }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }

    FormInput:
      type: object
      required: [name, email, is_verified, movie_id, type, payment_method, payment_status, number_of_goods_tickets, number_of_seat_tickets]
      properties:
        name: { type: string }
        email: { type: string }
        is_verified: { type: boolean }
        movie_id: { type: string }
        type:
          $ref: '#/components/schemas/FormType'
        payment_method:
          $ref: '#/components/schemas/PaymentMethod'
        payment_status:
          $ref: '#/components/schemas/PaymentStatus'
        number_of_goods_tickets: { type: integer }
        number_of_seat_tickets: { type: integer }
        is_deleted: { type: boolean }
        remarks: { type: string, nullable: true }
    
    FormType:
      type: string
      enum: [staff, crowdfunding, preorder, onTheDay]
    
    PaymentMethod:
      type: string
      enum: [cash, square, bank_transfer]

    PaymentStatus:
      type: string
      enum: [ not_contacted, pending, completed, failed]

    ########################################
    # Ticket
    ########################################
    Ticket:
      type: object
      properties:
        id: { type: string }
        form_id: { type: string }
        purpose:
          $ref: '#/components/schemas/TicketPurpose'
        is_used: { type: boolean }
        is_activated: { type: boolean }
        sheet_id: { type: string, nullable: true }
        movie_id: { type: string }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
        is_deleted: { type: boolean }

    TicketInput:
      type: object
      required: [form_id, purpose, is_used, is_activated, movie_id]
      properties:
        form_id: { type: string }
        purpose:
          $ref: '#/components/schemas/TicketPurpose'
        is_used: { type: boolean }
        is_activated: { type: boolean }
        sheet_id: { type: string, nullable: true }
        movie_id: { type: string }
        is_deleted: { type: boolean }

    TicketPurpose:
      type: string
      enum: [seat, goods]

    ########################################
    # Movie
    ########################################
    Movie:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        onair: { type: string, format: date-time }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }

    MovieInput:
      type: object
      required: [title, onair]
      properties:
        title: { type: string }
        onair: { type: string, format: date-time }

    ########################################
    # Sheet
    ########################################
    Sheet:
      type: object
      properties:
        id: { type: string }
        row: { type: string }
        col: { type: integer }
        status:
          type: string
          enum: [available, reserved, used]
        movie_id: { type: string }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }

    SheetInput:
      type: object
      required: [row, col, status]
      properties:
        row: { type: string }
        col: { type: integer }
        status:
          type: string
          enum: [available, reserved, used]
