/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List forms */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            page?: number;
                            limit?: number;
                            total?: number;
                            users?: components["schemas"]["Form"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new form */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FormInput"];
                };
            };
            responses: {
                /** @description Form created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/{formId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific form */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
            };
        };
        /** Replace a form */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FormInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a user partially */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tickets */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            page?: number;
                            limit?: number;
                            total?: number;
                            tickets?: components["schemas"]["Ticket"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create tickets
         * @description Creates one or more tickets for a user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        form_id: string;
                    };
                };
            };
            responses: {
                /** @description Tickets created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a ticket */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"];
                    };
                };
            };
        };
        /** Replace a ticket */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TicketInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a ticket */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a ticket partially */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List movies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Movie"][];
                    };
                };
            };
        };
        put?: never;
        /** Create movie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MovieInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movieId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get movie */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Movie"];
                    };
                };
            };
        };
        /** Replace movie */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MovieInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete movie */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movieId}/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List seats for a movie */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sheet"][];
                    };
                };
            };
        };
        put?: never;
        /** Create seats for a movie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SheetInput"];
                };
            };
            responses: {
                /** @description Sheet Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movieId}/sheets/{sheetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get seat info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                    sheetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sheet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete seat */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                    sheetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update seat */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                    sheetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Form: {
            id?: string;
            name?: string;
            email?: string;
            is_verified?: boolean;
            payment_method?: components["schemas"]["PaymentMethod"];
            payment_status?: components["schemas"]["PaymentStatus"];
            number_of_tickets?: number;
            number_of_sheets?: number;
            remarks?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        FormInput: {
            name: string;
            email: string;
            is_verified: boolean;
            payment_method: components["schemas"]["PaymentMethod"];
            payment_status?: components["schemas"]["PaymentStatus"];
            number_of_tickets: number;
            number_of_sheets: number;
            remarks?: string | null;
        };
        /** @enum {string} */
        PaymentMethod: "cash" | "paypay" | "bank_transfer";
        /** @enum {string} */
        PaymentStatus: "not_contacted" | "pending" | "completed" | "failed";
        Ticket: {
            id?: string;
            form_id?: string;
            purpose?: components["schemas"]["TicketPurpose"];
            type?: components["schemas"]["TicketType"];
            is_used?: boolean;
            is_activated?: boolean;
            sheet_id?: string | null;
            movie_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TicketInput: {
            form_id: string;
            purpose: components["schemas"]["TicketPurpose"];
            type: components["schemas"]["TicketType"];
            is_used: boolean;
            is_activated: boolean;
            sheet_id?: string | null;
            movie_id: string;
        };
        /** @enum {string} */
        TicketPurpose: "seat" | "goods";
        /** @enum {string} */
        TicketType: "staff" | "crowdfunding" | "preorder" | "onTheDay";
        Movie: {
            id?: string;
            title?: string;
            /** Format: date-time */
            onair?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MovieInput: {
            title: string;
            /** Format: date-time */
            onair: string;
        };
        Sheet: {
            id?: string;
            row?: string;
            col?: number;
            /** @enum {string} */
            status?: "available" | "reserved" | "used";
            movie_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SheetInput: {
            row: string;
            col: number;
            /** @enum {string} */
            status: "available" | "reserved" | "used";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
