/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin - Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin - List forms
         * @description Retrieve all forms excluding those marked as deleted (is_deleted: true).
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            page?: number;
                            limit?: number;
                            total?: number;
                            forms?: components["schemas"]["Form"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/forms/{formId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin - Get a specific form */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
            };
        };
        /** Admin - Replace a form */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FormInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Admin - Soft delete a form
         * @description Mark the form as deleted by setting `is_deleted` to `true`.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin - List tickets */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            page?: number;
                            limit?: number;
                            total?: number;
                            tickets?: components["schemas"]["Ticket"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin - Get a ticket */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"];
                    };
                };
            };
        };
        /** Admin - Replace a ticket */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TicketInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Admin - Soft delete a ticket
         * @description Mark the ticket as deleted by setting `is_deleted` to `true`.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin - List movies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Movie"][];
                    };
                };
            };
        };
        put?: never;
        /** Admin - Create movie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MovieInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/movies/{movieId}/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin - List seats for a movie */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sheet"][];
                    };
                };
            };
        };
        put?: never;
        /** Admin - Create seats for a movie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SheetInput"];
                };
            };
            responses: {
                /** @description Sheet Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/movies/{movieId}/sheets/{sheetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin - Get seat info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                    sheetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Sheet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Admin - Delete seat */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                    sheetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Admin - Update seat */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    movieId: string;
                    sheetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/user/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User - Create a new form */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FormInput"];
                };
            };
            responses: {
                /** @description Form created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/forms/{formId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User - Get a specific form */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/tickets/form/{formId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User - List tickets by form */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** User - Update a ticket */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TicketInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Form: {
            id?: string;
            name?: string;
            email?: string;
            is_verified?: boolean;
            movie_id?: string;
            type?: components["schemas"]["FormType"];
            payment_method?: components["schemas"]["PaymentMethod"];
            payment_status?: components["schemas"]["PaymentStatus"];
            number_of_goods_tickets?: number;
            number_of_seat_tickets?: number;
            is_deleted?: boolean;
            remarks?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        FormInput: {
            name: string;
            email: string;
            is_verified: boolean;
            movie_id: string;
            type: components["schemas"]["FormType"];
            payment_method: components["schemas"]["PaymentMethod"];
            payment_status: components["schemas"]["PaymentStatus"];
            number_of_goods_tickets: number;
            number_of_seat_tickets: number;
            is_deleted?: boolean;
            remarks?: string | null;
        };
        /** @enum {string} */
        FormType: "staff" | "crowdfunding" | "preorder" | "onTheDay";
        /** @enum {string} */
        PaymentMethod: "cash" | "square" | "bank_transfer";
        /** @enum {string} */
        PaymentStatus: "not_contacted" | "pending" | "completed" | "failed";
        Ticket: {
            id?: string;
            form_id?: string;
            purpose?: components["schemas"]["TicketPurpose"];
            is_used?: boolean;
            is_activated?: boolean;
            sheet_id?: string | null;
            movie_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            is_deleted?: boolean;
        };
        TicketInput: {
            form_id: string;
            purpose: components["schemas"]["TicketPurpose"];
            is_used: boolean;
            is_activated: boolean;
            sheet_id?: string | null;
            movie_id: string;
            is_deleted?: boolean;
        };
        /** @enum {string} */
        TicketPurpose: "seat" | "goods";
        Movie: {
            id?: string;
            title?: string;
            /** Format: date-time */
            onair?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MovieInput: {
            title: string;
            /** Format: date-time */
            onair: string;
        };
        Sheet: {
            id?: string;
            row?: string;
            col?: number;
            /** @enum {string} */
            status?: "available" | "reserved" | "used";
            movie_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SheetInput: {
            row: string;
            col: number;
            /** @enum {string} */
            status: "available" | "reserved" | "used";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
